wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.11
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1686814093.183318
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.10.11
      5: 0.15.3
      8:
      - 1
      - 3
      - 5
